site_name: DIGITbrain Documentation
theme:
  name: material
  logo: img/db-logo.png
  favicon: img/db-logo.png
  palette:
    primary: teal
    accent: cyan
  features:
    - navigation.instant
    - navigation.tabs
nav:
  - Home: index.md
  - Getting Started: start.md
  - Publishing Assets:
      - Microservice: microservice.md
      - Algorithm: algorithm.md
      - Model: model.md
      - Data: data.md
      - MA Pair: ma_pair.md
      - DMA Tuple: dma_tuple.md
      - Deployment: deployment.md
      - Supporting Metadata: supporting_metadata.md
      - Metadata Tables:
          - tables/microservice.md
          - tables/algorithm.md
          - tables/model.md
          - MA Pair: tables/ma_pair.md
          - tables/data.md
          - tables/deployment.md
          - DMA Tuple: tables/dma_tuple.md
          - Supporting Metadata: tables/supporting_metadata.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
