site_name: DIGITbrain Documentation
repo_url: https://github.com/digitbrain/metadata
edit_uri: edit/main/docs
theme:
  name: material
  logo: img/db-logo.png
  favicon: img/db-logo.png
  palette:
    primary: teal
    accent: cyan
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home: index.md
  - Getting Started: start.md
  - Assets Overview:
      - Microservice: microservice.md
      - Algorithm: algorithm.md
      - Model: model.md
      - Data: data.md
      - MA Pair: ma_pair.md
      - DMA Tuple: dma_tuple.md
      - Supporting Metadata: supporting_metadata.md
      - Substructures:
          - Data Assets Mapping: dataassetsmapping.md
          - Deployment: deployment.md
  - Asset Detail:
      - Microservice: attributes/microservice.md
      - Algorithm: attributes/algorithm.md
      - Model: attributes/model.md
      - Data: attributes/data.md
      - MA Pair: attributes/ma_pair.md
      - DMA Tuple: attributes/dma_tuple.md
      - Supporting Metadata: attributes/supporting_metadata.md
      - Substructures:
          - Data Assets Mapping: attributes/dataassetsmapping.md
          - Deployment: attributes/deployment.md
  - Asset Tables:
      - tables/microservice.md
      - tables/algorithm.md
      - tables/model.md
      - tables/data.md
      - MA Pair: tables/ma_pair.md
      - DMA Tuple: tables/dma_tuple.md
      - Supporting Metadata: tables/supporting_metadata.md
      - Substructures:
          - Data Assets Mapping: tables/dataassetsmapping.md
          - tables/deployment.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
