# This is a basic workflow to help you get started with Actions

name: Generate csv files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Generate docs from Excel
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel pandas openpyxl mdtable jinja2

      - name: Run xls2csv
        run: python tools/xls2md.py

      - name: Run xls2mkdocs
        run: python tools/xls2mkdocs.py
        
      - name: Run exceltojson
        run: python tools/exceltojson.py

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: ${{ github.event.head_commit.message }} [AUTO]
          file_pattern: docs/*/*.md

  publish:
    name: Publish the site
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      
      - name: Install Mkdocs
        run: pip install mkdocs-material

      - name: Point to digitbrain.github.io
        run: |
          git remote rm origin
          git remote add origin https://x-access-token:${PERSONAL_TOKEN}@github.com/digitbrain.github.io.git
          git fetch
      
      - name: Run Mkdocs deploy
        run: mkdocs gh-deploy